### ISSUE TITLE
Crash in ScummVM - Paladin endgame

### ISSUE THREAD

**Issue by tomasz89** [AshLancer/QFG3-Fan-Patch#5]
I have posted this to ScummVM as #11477 (https://bugs.scummvm.org/ticket/11477) too as I'm not sure where the problem lies - with the script modifications done here or ScummVM.

QFG3 with AshLancer's patches v1.3.1A (​https://github.com/AshLancer/QFG3-Fan-Patch/issues)
ScummVM 2.2.0git5534-gce11c13ffa on Ubuntu 20.04 64bit.

I throw my Paladin sword at the Demon Wizard only to get a crash:
Uninitialized read for temp 1 from method ProjObj::doit (room 852, script 32, localCall ffffffff)!

**Comment by AshLancer** [comment]
Hello, sorry for not replying!

This may be a scummVM issue. I tested throwing the sword at the Demon Wizard many, many times on DosBox and under several speed settings. Will attempt to reproduce it using ScummVM.

**Comment by tomasz89** [comment]
It was a ScummVM issue - and has now been fixed in ScummVM #11477.
